//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Laba_2.MyAsmxService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DocumentsWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DocumentsWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetDocumentBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDocumentInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDocumentRecieptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSpecialDocumentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DocumentsWebService() {
            this.Url = global::Laba_2.Properties.Settings.Default.Laba_2_MyAsmxService_DocumentsWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetDocumentBillCompletedEventHandler SetDocumentBillCompleted;
        
        /// <remarks/>
        public event SetDocumentInvoiceCompletedEventHandler SetDocumentInvoiceCompleted;
        
        /// <remarks/>
        public event SetDocumentRecieptCompletedEventHandler SetDocumentRecieptCompleted;
        
        /// <remarks/>
        public event GetAllDocumentsCompletedEventHandler GetAllDocumentsCompleted;
        
        /// <remarks/>
        public event GetSpecialDocumentsCompletedEventHandler GetSpecialDocumentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetDocumentBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetDocumentBill(string[] data, Product[] products, string pathToFile) {
            object[] results = this.Invoke("SetDocumentBill", new object[] {
                        data,
                        products,
                        pathToFile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetDocumentBillAsync(string[] data, Product[] products, string pathToFile) {
            this.SetDocumentBillAsync(data, products, pathToFile, null);
        }
        
        /// <remarks/>
        public void SetDocumentBillAsync(string[] data, Product[] products, string pathToFile, object userState) {
            if ((this.SetDocumentBillOperationCompleted == null)) {
                this.SetDocumentBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDocumentBillOperationCompleted);
            }
            this.InvokeAsync("SetDocumentBill", new object[] {
                        data,
                        products,
                        pathToFile}, this.SetDocumentBillOperationCompleted, userState);
        }
        
        private void OnSetDocumentBillOperationCompleted(object arg) {
            if ((this.SetDocumentBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDocumentBillCompleted(this, new SetDocumentBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetDocumentInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetDocumentInvoice(string[] data, Product[] products, string pathToFile) {
            object[] results = this.Invoke("SetDocumentInvoice", new object[] {
                        data,
                        products,
                        pathToFile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetDocumentInvoiceAsync(string[] data, Product[] products, string pathToFile) {
            this.SetDocumentInvoiceAsync(data, products, pathToFile, null);
        }
        
        /// <remarks/>
        public void SetDocumentInvoiceAsync(string[] data, Product[] products, string pathToFile, object userState) {
            if ((this.SetDocumentInvoiceOperationCompleted == null)) {
                this.SetDocumentInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDocumentInvoiceOperationCompleted);
            }
            this.InvokeAsync("SetDocumentInvoice", new object[] {
                        data,
                        products,
                        pathToFile}, this.SetDocumentInvoiceOperationCompleted, userState);
        }
        
        private void OnSetDocumentInvoiceOperationCompleted(object arg) {
            if ((this.SetDocumentInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDocumentInvoiceCompleted(this, new SetDocumentInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetDocumentReciept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetDocumentReciept(string[] data, Product[] products, string pathToFile) {
            object[] results = this.Invoke("SetDocumentReciept", new object[] {
                        data,
                        products,
                        pathToFile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetDocumentRecieptAsync(string[] data, Product[] products, string pathToFile) {
            this.SetDocumentRecieptAsync(data, products, pathToFile, null);
        }
        
        /// <remarks/>
        public void SetDocumentRecieptAsync(string[] data, Product[] products, string pathToFile, object userState) {
            if ((this.SetDocumentRecieptOperationCompleted == null)) {
                this.SetDocumentRecieptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDocumentRecieptOperationCompleted);
            }
            this.InvokeAsync("SetDocumentReciept", new object[] {
                        data,
                        products,
                        pathToFile}, this.SetDocumentRecieptOperationCompleted, userState);
        }
        
        private void OnSetDocumentRecieptOperationCompleted(object arg) {
            if ((this.SetDocumentRecieptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDocumentRecieptCompleted(this, new SetDocumentRecieptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllDocuments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Document[] GetAllDocuments(string pathToFile) {
            object[] results = this.Invoke("GetAllDocuments", new object[] {
                        pathToFile});
            return ((Document[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDocumentsAsync(string pathToFile) {
            this.GetAllDocumentsAsync(pathToFile, null);
        }
        
        /// <remarks/>
        public void GetAllDocumentsAsync(string pathToFile, object userState) {
            if ((this.GetAllDocumentsOperationCompleted == null)) {
                this.GetAllDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDocumentsOperationCompleted);
            }
            this.InvokeAsync("GetAllDocuments", new object[] {
                        pathToFile}, this.GetAllDocumentsOperationCompleted, userState);
        }
        
        private void OnGetAllDocumentsOperationCompleted(object arg) {
            if ((this.GetAllDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDocumentsCompleted(this, new GetAllDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSpecialDocuments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Document[] GetSpecialDocuments(string pathToFile, string type) {
            object[] results = this.Invoke("GetSpecialDocuments", new object[] {
                        pathToFile,
                        type});
            return ((Document[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSpecialDocumentsAsync(string pathToFile, string type) {
            this.GetSpecialDocumentsAsync(pathToFile, type, null);
        }
        
        /// <remarks/>
        public void GetSpecialDocumentsAsync(string pathToFile, string type, object userState) {
            if ((this.GetSpecialDocumentsOperationCompleted == null)) {
                this.GetSpecialDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSpecialDocumentsOperationCompleted);
            }
            this.InvokeAsync("GetSpecialDocuments", new object[] {
                        pathToFile,
                        type}, this.GetSpecialDocumentsOperationCompleted, userState);
        }
        
        private void OnGetSpecialDocumentsOperationCompleted(object arg) {
            if ((this.GetSpecialDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSpecialDocumentsCompleted(this, new GetSpecialDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Product {
        
        private string nameField;
        
        private string measureUnitField;
        
        private int countField;
        
        private double priceField;
        
        private double sumField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string MeasureUnit {
            get {
                return this.measureUnitField;
            }
            set {
                this.measureUnitField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public double Sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Invoice))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bill))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Reciept))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Document {
        
        private string docIdField;
        
        private System.DateTime docDateField;
        
        private string providerField;
        
        private string clientField;
        
        /// <remarks/>
        public string DocId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DocDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Invoice : Document {
        
        private Product[] productsField;
        
        private string clientIdField;
        
        private string providerIdField;
        
        private double goodsSumField;
        
        /// <remarks/>
        public Product[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProviderId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
            }
        }
        
        /// <remarks/>
        public double GoodsSum {
            get {
                return this.goodsSumField;
            }
            set {
                this.goodsSumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bill : Document {
        
        private Product[] productsField;
        
        private string clientIdField;
        
        private double goodsSumField;
        
        /// <remarks/>
        public Product[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public double GoodsSum {
            get {
                return this.goodsSumField;
            }
            set {
                this.goodsSumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reciept : Document {
        
        private Product[] productsField;
        
        private double goodsSumField;
        
        private string paymentNameField;
        
        /// <remarks/>
        public Product[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        public double GoodsSum {
            get {
                return this.goodsSumField;
            }
            set {
                this.goodsSumField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentName {
            get {
                return this.paymentNameField;
            }
            set {
                this.paymentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SetDocumentBillCompletedEventHandler(object sender, SetDocumentBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetDocumentBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDocumentBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SetDocumentInvoiceCompletedEventHandler(object sender, SetDocumentInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetDocumentInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDocumentInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SetDocumentRecieptCompletedEventHandler(object sender, SetDocumentRecieptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetDocumentRecieptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDocumentRecieptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetAllDocumentsCompletedEventHandler(object sender, GetAllDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Document[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Document[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetSpecialDocumentsCompletedEventHandler(object sender, GetSpecialDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSpecialDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSpecialDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Document[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Document[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591