//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciepts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reciepts()
        {
            this.Products = new HashSet<Products>();
        }
    
        public string DocId { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Provider { get; set; }
        public string Client { get; set; }
        public string PaymentName { get; set; }
        public decimal GoodSum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
