//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_7.MyWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureUnitField;
        
        private int CountField;
        
        private double PriceField;
        
        private double SumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MeasureUnit {
            get {
                return this.MeasureUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureUnitField, value) != true)) {
                    this.MeasureUnitField = value;
                    this.RaisePropertyChanged("MeasureUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laba_7.MyWcfService.Reciept))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laba_7.MyWcfService.Bill))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laba_7.MyWcfService.Invoice))]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIdField;
        
        private System.DateTime DocDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocId {
            get {
                return this.DocIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIdField, value) != true)) {
                    this.DocIdField = value;
                    this.RaisePropertyChanged("DocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DocDate {
            get {
                return this.DocDateField;
            }
            set {
                if ((this.DocDateField.Equals(value) != true)) {
                    this.DocDateField = value;
                    this.RaisePropertyChanged("DocDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reciept", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Reciept : Laba_7.MyWcfService.Document {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laba_7.MyWcfService.Product[] ProductsField;
        
        private double GoodsSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Laba_7.MyWcfService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double GoodsSum {
            get {
                return this.GoodsSumField;
            }
            set {
                if ((this.GoodsSumField.Equals(value) != true)) {
                    this.GoodsSumField = value;
                    this.RaisePropertyChanged("GoodsSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PaymentName {
            get {
                return this.PaymentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentNameField, value) != true)) {
                    this.PaymentNameField = value;
                    this.RaisePropertyChanged("PaymentName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bill", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Bill : Laba_7.MyWcfService.Document {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laba_7.MyWcfService.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        private double GoodsSumField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Laba_7.MyWcfService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double GoodsSum {
            get {
                return this.GoodsSumField;
            }
            set {
                if ((this.GoodsSumField.Equals(value) != true)) {
                    this.GoodsSumField = value;
                    this.RaisePropertyChanged("GoodsSum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Invoice : Laba_7.MyWcfService.Document {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laba_7.MyWcfService.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderIdField;
        
        private double GoodsSumField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Laba_7.MyWcfService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderIdField, value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double GoodsSum {
            get {
                return this.GoodsSumField;
            }
            set {
                if ((this.GoodsSumField.Equals(value) != true)) {
                    this.GoodsSumField = value;
                    this.RaisePropertyChanged("GoodsSum");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWcfService.IDocumentsWebServiceWcf")]
    public interface IDocumentsWebServiceWcf {
        
        // CODEGEN: Контракт генерации сообщений с именем data из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentBill", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentBillResponse")]
        Laba_7.MyWcfService.SetDocumentBillResponse SetDocumentBill(Laba_7.MyWcfService.SetDocumentBillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentBill", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentBillResponse")]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentBillResponse> SetDocumentBillAsync(Laba_7.MyWcfService.SetDocumentBillRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем data из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentInvoice", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentInvoiceResponse")]
        Laba_7.MyWcfService.SetDocumentInvoiceResponse SetDocumentInvoice(Laba_7.MyWcfService.SetDocumentInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentInvoice", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentInvoiceResponse")]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentInvoiceResponse> SetDocumentInvoiceAsync(Laba_7.MyWcfService.SetDocumentInvoiceRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем data из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentReciept", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentRecieptResponse")]
        Laba_7.MyWcfService.SetDocumentRecieptResponse SetDocumentReciept(Laba_7.MyWcfService.SetDocumentRecieptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentReciept", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/SetDocumentRecieptResponse")]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentRecieptResponse> SetDocumentRecieptAsync(Laba_7.MyWcfService.SetDocumentRecieptRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetAllDocumentsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/GetAllDocuments", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/GetAllDocumentsResponse")]
        Laba_7.MyWcfService.GetAllDocumentsResponse GetAllDocuments(Laba_7.MyWcfService.GetAllDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/GetAllDocuments", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/GetAllDocumentsResponse")]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.GetAllDocumentsResponse> GetAllDocumentsAsync(Laba_7.MyWcfService.GetAllDocumentsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем type из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocuments", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocumentsResponse")]
        Laba_7.MyWcfService.GetSpecialDocumentsResponse GetSpecialDocuments(Laba_7.MyWcfService.GetSpecialDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocuments", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocumentsResponse")]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.GetSpecialDocumentsResponse> GetSpecialDocumentsAsync(Laba_7.MyWcfService.GetSpecialDocumentsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем docId из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocument", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocumentResponse")]
        Laba_7.MyWcfService.GetSpecialDocumentResponse GetSpecialDocument(Laba_7.MyWcfService.GetSpecialDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocument", ReplyAction="http://tempuri.org/IDocumentsWebServiceWcf/GetSpecialDocumentResponse")]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.GetSpecialDocumentResponse> GetSpecialDocumentAsync(Laba_7.MyWcfService.GetSpecialDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentBill", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.SetDocumentBillRequestBody Body;
        
        public SetDocumentBillRequest() {
        }
        
        public SetDocumentBillRequest(Laba_7.MyWcfService.SetDocumentBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDocumentBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laba_7.MyWcfService.ArrayOfString data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Laba_7.MyWcfService.Product[] productsPacket;
        
        public SetDocumentBillRequestBody() {
        }
        
        public SetDocumentBillRequestBody(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            this.data = data;
            this.productsPacket = productsPacket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentBillResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.SetDocumentBillResponseBody Body;
        
        public SetDocumentBillResponse() {
        }
        
        public SetDocumentBillResponse(Laba_7.MyWcfService.SetDocumentBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDocumentBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetDocumentBillResult;
        
        public SetDocumentBillResponseBody() {
        }
        
        public SetDocumentBillResponseBody(bool SetDocumentBillResult) {
            this.SetDocumentBillResult = SetDocumentBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentInvoice", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.SetDocumentInvoiceRequestBody Body;
        
        public SetDocumentInvoiceRequest() {
        }
        
        public SetDocumentInvoiceRequest(Laba_7.MyWcfService.SetDocumentInvoiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDocumentInvoiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laba_7.MyWcfService.ArrayOfString data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Laba_7.MyWcfService.Product[] productsPacket;
        
        public SetDocumentInvoiceRequestBody() {
        }
        
        public SetDocumentInvoiceRequestBody(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            this.data = data;
            this.productsPacket = productsPacket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentInvoiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.SetDocumentInvoiceResponseBody Body;
        
        public SetDocumentInvoiceResponse() {
        }
        
        public SetDocumentInvoiceResponse(Laba_7.MyWcfService.SetDocumentInvoiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDocumentInvoiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetDocumentInvoiceResult;
        
        public SetDocumentInvoiceResponseBody() {
        }
        
        public SetDocumentInvoiceResponseBody(bool SetDocumentInvoiceResult) {
            this.SetDocumentInvoiceResult = SetDocumentInvoiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentRecieptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentReciept", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.SetDocumentRecieptRequestBody Body;
        
        public SetDocumentRecieptRequest() {
        }
        
        public SetDocumentRecieptRequest(Laba_7.MyWcfService.SetDocumentRecieptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDocumentRecieptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laba_7.MyWcfService.ArrayOfString data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Laba_7.MyWcfService.Product[] productsPacket;
        
        public SetDocumentRecieptRequestBody() {
        }
        
        public SetDocumentRecieptRequestBody(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            this.data = data;
            this.productsPacket = productsPacket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentRecieptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentRecieptResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.SetDocumentRecieptResponseBody Body;
        
        public SetDocumentRecieptResponse() {
        }
        
        public SetDocumentRecieptResponse(Laba_7.MyWcfService.SetDocumentRecieptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDocumentRecieptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetDocumentRecieptResult;
        
        public SetDocumentRecieptResponseBody() {
        }
        
        public SetDocumentRecieptResponseBody(bool SetDocumentRecieptResult) {
            this.SetDocumentRecieptResult = SetDocumentRecieptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDocuments", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.GetAllDocumentsRequestBody Body;
        
        public GetAllDocumentsRequest() {
        }
        
        public GetAllDocumentsRequest(Laba_7.MyWcfService.GetAllDocumentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDocumentsRequestBody {
        
        public GetAllDocumentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDocumentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.GetAllDocumentsResponseBody Body;
        
        public GetAllDocumentsResponse() {
        }
        
        public GetAllDocumentsResponse(Laba_7.MyWcfService.GetAllDocumentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDocumentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laba_7.MyWcfService.Document[] GetAllDocumentsResult;
        
        public GetAllDocumentsResponseBody() {
        }
        
        public GetAllDocumentsResponseBody(Laba_7.MyWcfService.Document[] GetAllDocumentsResult) {
            this.GetAllDocumentsResult = GetAllDocumentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpecialDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpecialDocuments", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.GetSpecialDocumentsRequestBody Body;
        
        public GetSpecialDocumentsRequest() {
        }
        
        public GetSpecialDocumentsRequest(Laba_7.MyWcfService.GetSpecialDocumentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpecialDocumentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        public GetSpecialDocumentsRequestBody() {
        }
        
        public GetSpecialDocumentsRequestBody(string type) {
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpecialDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpecialDocumentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.GetSpecialDocumentsResponseBody Body;
        
        public GetSpecialDocumentsResponse() {
        }
        
        public GetSpecialDocumentsResponse(Laba_7.MyWcfService.GetSpecialDocumentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpecialDocumentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laba_7.MyWcfService.Document[] GetSpecialDocumentsResult;
        
        public GetSpecialDocumentsResponseBody() {
        }
        
        public GetSpecialDocumentsResponseBody(Laba_7.MyWcfService.Document[] GetSpecialDocumentsResult) {
            this.GetSpecialDocumentsResult = GetSpecialDocumentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpecialDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpecialDocument", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.GetSpecialDocumentRequestBody Body;
        
        public GetSpecialDocumentRequest() {
        }
        
        public GetSpecialDocumentRequest(Laba_7.MyWcfService.GetSpecialDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpecialDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docId;
        
        public GetSpecialDocumentRequestBody() {
        }
        
        public GetSpecialDocumentRequestBody(string docId) {
            this.docId = docId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpecialDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpecialDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laba_7.MyWcfService.GetSpecialDocumentResponseBody Body;
        
        public GetSpecialDocumentResponse() {
        }
        
        public GetSpecialDocumentResponse(Laba_7.MyWcfService.GetSpecialDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpecialDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laba_7.MyWcfService.Document[] GetSpecialDocumentResult;
        
        public GetSpecialDocumentResponseBody() {
        }
        
        public GetSpecialDocumentResponseBody(Laba_7.MyWcfService.Document[] GetSpecialDocumentResult) {
            this.GetSpecialDocumentResult = GetSpecialDocumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentsWebServiceWcfChannel : Laba_7.MyWcfService.IDocumentsWebServiceWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentsWebServiceWcfClient : System.ServiceModel.ClientBase<Laba_7.MyWcfService.IDocumentsWebServiceWcf>, Laba_7.MyWcfService.IDocumentsWebServiceWcf {
        
        public DocumentsWebServiceWcfClient() {
        }
        
        public DocumentsWebServiceWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentsWebServiceWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsWebServiceWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsWebServiceWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laba_7.MyWcfService.SetDocumentBillResponse Laba_7.MyWcfService.IDocumentsWebServiceWcf.SetDocumentBill(Laba_7.MyWcfService.SetDocumentBillRequest request) {
            return base.Channel.SetDocumentBill(request);
        }
        
        public bool SetDocumentBill(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            Laba_7.MyWcfService.SetDocumentBillRequest inValue = new Laba_7.MyWcfService.SetDocumentBillRequest();
            inValue.Body = new Laba_7.MyWcfService.SetDocumentBillRequestBody();
            inValue.Body.data = data;
            inValue.Body.productsPacket = productsPacket;
            Laba_7.MyWcfService.SetDocumentBillResponse retVal = ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).SetDocumentBill(inValue);
            return retVal.Body.SetDocumentBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentBillResponse> Laba_7.MyWcfService.IDocumentsWebServiceWcf.SetDocumentBillAsync(Laba_7.MyWcfService.SetDocumentBillRequest request) {
            return base.Channel.SetDocumentBillAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentBillResponse> SetDocumentBillAsync(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            Laba_7.MyWcfService.SetDocumentBillRequest inValue = new Laba_7.MyWcfService.SetDocumentBillRequest();
            inValue.Body = new Laba_7.MyWcfService.SetDocumentBillRequestBody();
            inValue.Body.data = data;
            inValue.Body.productsPacket = productsPacket;
            return ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).SetDocumentBillAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laba_7.MyWcfService.SetDocumentInvoiceResponse Laba_7.MyWcfService.IDocumentsWebServiceWcf.SetDocumentInvoice(Laba_7.MyWcfService.SetDocumentInvoiceRequest request) {
            return base.Channel.SetDocumentInvoice(request);
        }
        
        public bool SetDocumentInvoice(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            Laba_7.MyWcfService.SetDocumentInvoiceRequest inValue = new Laba_7.MyWcfService.SetDocumentInvoiceRequest();
            inValue.Body = new Laba_7.MyWcfService.SetDocumentInvoiceRequestBody();
            inValue.Body.data = data;
            inValue.Body.productsPacket = productsPacket;
            Laba_7.MyWcfService.SetDocumentInvoiceResponse retVal = ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).SetDocumentInvoice(inValue);
            return retVal.Body.SetDocumentInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentInvoiceResponse> Laba_7.MyWcfService.IDocumentsWebServiceWcf.SetDocumentInvoiceAsync(Laba_7.MyWcfService.SetDocumentInvoiceRequest request) {
            return base.Channel.SetDocumentInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentInvoiceResponse> SetDocumentInvoiceAsync(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            Laba_7.MyWcfService.SetDocumentInvoiceRequest inValue = new Laba_7.MyWcfService.SetDocumentInvoiceRequest();
            inValue.Body = new Laba_7.MyWcfService.SetDocumentInvoiceRequestBody();
            inValue.Body.data = data;
            inValue.Body.productsPacket = productsPacket;
            return ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).SetDocumentInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laba_7.MyWcfService.SetDocumentRecieptResponse Laba_7.MyWcfService.IDocumentsWebServiceWcf.SetDocumentReciept(Laba_7.MyWcfService.SetDocumentRecieptRequest request) {
            return base.Channel.SetDocumentReciept(request);
        }
        
        public bool SetDocumentReciept(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            Laba_7.MyWcfService.SetDocumentRecieptRequest inValue = new Laba_7.MyWcfService.SetDocumentRecieptRequest();
            inValue.Body = new Laba_7.MyWcfService.SetDocumentRecieptRequestBody();
            inValue.Body.data = data;
            inValue.Body.productsPacket = productsPacket;
            Laba_7.MyWcfService.SetDocumentRecieptResponse retVal = ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).SetDocumentReciept(inValue);
            return retVal.Body.SetDocumentRecieptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentRecieptResponse> Laba_7.MyWcfService.IDocumentsWebServiceWcf.SetDocumentRecieptAsync(Laba_7.MyWcfService.SetDocumentRecieptRequest request) {
            return base.Channel.SetDocumentRecieptAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laba_7.MyWcfService.SetDocumentRecieptResponse> SetDocumentRecieptAsync(Laba_7.MyWcfService.ArrayOfString data, Laba_7.MyWcfService.Product[] productsPacket) {
            Laba_7.MyWcfService.SetDocumentRecieptRequest inValue = new Laba_7.MyWcfService.SetDocumentRecieptRequest();
            inValue.Body = new Laba_7.MyWcfService.SetDocumentRecieptRequestBody();
            inValue.Body.data = data;
            inValue.Body.productsPacket = productsPacket;
            return ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).SetDocumentRecieptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laba_7.MyWcfService.GetAllDocumentsResponse Laba_7.MyWcfService.IDocumentsWebServiceWcf.GetAllDocuments(Laba_7.MyWcfService.GetAllDocumentsRequest request) {
            return base.Channel.GetAllDocuments(request);
        }
        
        public Laba_7.MyWcfService.Document[] GetAllDocuments() {
            Laba_7.MyWcfService.GetAllDocumentsRequest inValue = new Laba_7.MyWcfService.GetAllDocumentsRequest();
            inValue.Body = new Laba_7.MyWcfService.GetAllDocumentsRequestBody();
            Laba_7.MyWcfService.GetAllDocumentsResponse retVal = ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).GetAllDocuments(inValue);
            return retVal.Body.GetAllDocumentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.GetAllDocumentsResponse> Laba_7.MyWcfService.IDocumentsWebServiceWcf.GetAllDocumentsAsync(Laba_7.MyWcfService.GetAllDocumentsRequest request) {
            return base.Channel.GetAllDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laba_7.MyWcfService.GetAllDocumentsResponse> GetAllDocumentsAsync() {
            Laba_7.MyWcfService.GetAllDocumentsRequest inValue = new Laba_7.MyWcfService.GetAllDocumentsRequest();
            inValue.Body = new Laba_7.MyWcfService.GetAllDocumentsRequestBody();
            return ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).GetAllDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laba_7.MyWcfService.GetSpecialDocumentsResponse Laba_7.MyWcfService.IDocumentsWebServiceWcf.GetSpecialDocuments(Laba_7.MyWcfService.GetSpecialDocumentsRequest request) {
            return base.Channel.GetSpecialDocuments(request);
        }
        
        public Laba_7.MyWcfService.Document[] GetSpecialDocuments(string type) {
            Laba_7.MyWcfService.GetSpecialDocumentsRequest inValue = new Laba_7.MyWcfService.GetSpecialDocumentsRequest();
            inValue.Body = new Laba_7.MyWcfService.GetSpecialDocumentsRequestBody();
            inValue.Body.type = type;
            Laba_7.MyWcfService.GetSpecialDocumentsResponse retVal = ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).GetSpecialDocuments(inValue);
            return retVal.Body.GetSpecialDocumentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.GetSpecialDocumentsResponse> Laba_7.MyWcfService.IDocumentsWebServiceWcf.GetSpecialDocumentsAsync(Laba_7.MyWcfService.GetSpecialDocumentsRequest request) {
            return base.Channel.GetSpecialDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laba_7.MyWcfService.GetSpecialDocumentsResponse> GetSpecialDocumentsAsync(string type) {
            Laba_7.MyWcfService.GetSpecialDocumentsRequest inValue = new Laba_7.MyWcfService.GetSpecialDocumentsRequest();
            inValue.Body = new Laba_7.MyWcfService.GetSpecialDocumentsRequestBody();
            inValue.Body.type = type;
            return ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).GetSpecialDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laba_7.MyWcfService.GetSpecialDocumentResponse Laba_7.MyWcfService.IDocumentsWebServiceWcf.GetSpecialDocument(Laba_7.MyWcfService.GetSpecialDocumentRequest request) {
            return base.Channel.GetSpecialDocument(request);
        }
        
        public Laba_7.MyWcfService.Document[] GetSpecialDocument(string docId) {
            Laba_7.MyWcfService.GetSpecialDocumentRequest inValue = new Laba_7.MyWcfService.GetSpecialDocumentRequest();
            inValue.Body = new Laba_7.MyWcfService.GetSpecialDocumentRequestBody();
            inValue.Body.docId = docId;
            Laba_7.MyWcfService.GetSpecialDocumentResponse retVal = ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).GetSpecialDocument(inValue);
            return retVal.Body.GetSpecialDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laba_7.MyWcfService.GetSpecialDocumentResponse> Laba_7.MyWcfService.IDocumentsWebServiceWcf.GetSpecialDocumentAsync(Laba_7.MyWcfService.GetSpecialDocumentRequest request) {
            return base.Channel.GetSpecialDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laba_7.MyWcfService.GetSpecialDocumentResponse> GetSpecialDocumentAsync(string docId) {
            Laba_7.MyWcfService.GetSpecialDocumentRequest inValue = new Laba_7.MyWcfService.GetSpecialDocumentRequest();
            inValue.Body = new Laba_7.MyWcfService.GetSpecialDocumentRequestBody();
            inValue.Body.docId = docId;
            return ((Laba_7.MyWcfService.IDocumentsWebServiceWcf)(this)).GetSpecialDocumentAsync(inValue);
        }
    }
}
